export const products = [
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'lorem',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
		],
		imageTheater: ['Back', 'Outfit'],
	},
];
