export const products = [
	{
		model: 'PN20R',
		instrument: 'Violin',
		price: 360,
		short: 'A quality instrument at an affordable price',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shop in NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA25R',
		instrument: 'Viola',
		price: 550,
		short: 'A quality instrument at an affordable price',
		long: [
			'Assembled in our affiliated workshop',
			'Reddish brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Maple bridge and ebony fittings',
			"D'Addario Prelude strings",
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shop in NY, USA.',
			'Available in 15" to 16.5" sizes',
			'Outfit includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN30R',
		instrument: 'Violin',
		price: 590,
		short: 'A quality instrument at an affordable price',
		long: [
			'Assembled in our affiliated workshop',
			'Brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shop in NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA40R',
		instrument: 'Viola',
		price: 870,
		short: 'A quality instrument at an affordable price',
		long: [
			'Assembled in our affiliated workshop',
			'Brown Nitro lacquer finish',
			'Fully carved spruce top',
			'Fully carved maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Wittner-style metal tailpiece',
			'Each instrument is setup and inspected by hand in our violin shop in NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN55R',
		instrument: 'Violin',
		price: 750,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 1/8 to 4/4 sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PN55R-A',
		instrument: 'Violin',
		price: 930,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit A includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN55R-B',
		instrument: 'Violin',
		price: 1000,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit B includes molded plastic case, Glasser bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA60R',
		instrument: 'Viola',
		price: 890,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 12" to 16.5" sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PA60R-A',
		instrument: 'Viola',
		price: 1130,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 12" to 16.5" sizes',
			'Outfit A includes shaped case, wood bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA60R-B',
		instrument: 'Viola',
		price: 1410,
		short: 'An intermediate model, for more experienced musicians',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed antique spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Thomaastik Alphayue Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 12" to 16.5" sizes',
			'Outfit B includes molded plastic case, Glasser bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN100R',
		instrument: 'Violin',
		price: 1160,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed Golden Brown spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Four Wittner string adjusters',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 1/8 to 4/4 sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PN100R-A',
		instrument: 'Violin',
		price: 1500,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed Golden Brown spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Four Wittner string adjusters',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 1/8 to 4/4 sizes',
			'Outfit includes oblong case, Carbon Fiber bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA140R',
		instrument: 'Viola',
		price: 1320,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed Golden Brown spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Four Wittner string adjusters',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 12" to 16.5" sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PA140R-A',
		instrument: 'Viola',
		price: 1600,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Romanian workshop',
			'Hand rubbed Golden Brown spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Four Wittner string adjusters',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 12" to 16.5" sizes',
			'Outfit includes oblong case, Carbon Fiber bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN150R',
		instrument: 'Violin',
		price: 1600,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Prague workshop',
			'Hand rubbed Old World spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Ebony tailpiece with Wittner E adjuster',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 4/4 size only',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PN150R-A',
		instrument: 'Violin',
		price: 1970,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Prague workshop',
			'Hand rubbed Old World spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Ebony tailpiece with Wittner E adjuster',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 4/4 size only',
			'Outfit includes oblong case, Carbon Fiber bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PA165R',
		instrument: 'Viola',
		price: 2630,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Prague workshop',
			'Hand rubbed Old World spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Ebony tailpiece with Wittner A and D adjuster',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 15" to 16.5" sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PA165R-A',
		instrument: 'Viola',
		price: 3000,
		short: 'A professional model, ideal for college students',
		long: [
			'Assembled in our affiliated Prague workshop',
			'Hand rubbed Old World spirit varnish',
			'Fully hand carved Carpathian spruce top',
			'Fully hand carved Carpathian maple back and sides',
			'Highly seasoned French Maple bridge and ebony fittings',
			'Ebony tailpiece with Wittner A and D adjuster',
			'Thomaastik Dominant Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 15" to 16.5" sizes',
			'Outfit includes oblong case, Carbon Fiber bow, rosin',
		],
		imageTheater: ['Back', 'Outfit'],
	},
	{
		model: 'PN101R',
		instrument: 'Violin',
		price: 2820,
		short: 'A professional model, ideal for concert professionals',
		long: [
			'Expertly handcrafter master level violin',
			'Hand crafted within the IMC shop',
			'Beautifully antiquated oil varnish',
			'Highly seasoned fine vertical grain spruce top',
			'Highly seasoned figured maple back and sides',
			'Figured maple neck and scroll',
			'Figured seasoned artist French maple bridge',
			'Seasoned ebony fittings',
			'Wittner E adjuster',
			'Pirastro Evah Pirazzi Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 4/4 size only',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PA102R',
		instrument: 'Viola',
		price: 3750,
		short: 'A professional model, ideal for concert professionals',
		long: [
			'Expertly handcrafter master level viola',
			'Hand crafted within the IMC shop',
			'Beautifully antiquated oil varnish',
			'Highly seasoned fine vertical grain spruce top',
			'Highly seasoned figured maple back and sides',
			'Figured maple neck and scroll',
			'Figured seasoned artist French maple bridge',
			'Seasoned ebony fittings',
			'Wittner A and D adjuster',
			'Pirastro Evah Pirazzi Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 15-16.5in sizes',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PN600R',
		instrument: 'Violin',
		price: 3380,
		short: 'A professional model, ideal for concert professionals',
		long: [
			'Expertly handcrafter master level violin',
			'Assembled in our affiliate workshop in Prague',
			'Hand rubbed angique oil varnish',
			'Highly seasoned fine vertical grain spruce top',
			'Highly seasoned figured maple back and sides',
			'Moderately Figured maple neck and scroll',
			'Figured seasoned artist French maple bridge',
			'Highly Seasoned ebony fittings',
			'Wittner E adjuster',
			'Pirastro Evah Pirazzi Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 4/4 size only',
		],
		imageTheater: ['Back'],
	},
	{
		model: 'PA650R',
		instrument: 'Viola',
		price: 4500,
		short: 'A professional model, ideal for concert professionals',
		long: [
			'Expertly handcrafter master level viola',
			'Assembled in our affiliate workshop in Prague',
			'Hand rubbed angique oil varnish',
			'Highly seasoned fine vertical grain spruce top',
			'Highly seasoned figured maple back and sides',
			'Moderately Figured maple neck and scroll',
			'Figured seasoned artist French maple bridge',
			'Highly Seasoned ebony fittings',
			'Wittner E adjuster',
			'Pirastro Evah Pirazzi Strings',
			'Each instrument is setup and inspected by hand in our violin shopin NY, USA.',
			'Available in 4/4 size only',
		],
		imageTheater: ['Back'],
	},
];
